USE [master]
GO

/****** Object:  Database [DSGcontacts]    Script Date: 2023/03/09 20:14:35 ******/
CREATE DATABASE [DSGcontacts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DSGcontacts', FILENAME = N'C:\Users\Banele\DSGcontacts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DSGcontacts_log', FILENAME = N'C:\Users\Banele\DSGcontacts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DSGcontacts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DSGcontacts] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DSGcontacts] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DSGcontacts] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DSGcontacts] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DSGcontacts] SET ARITHABORT OFF 
GO

ALTER DATABASE [DSGcontacts] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DSGcontacts] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DSGcontacts] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DSGcontacts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DSGcontacts] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DSGcontacts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DSGcontacts] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DSGcontacts] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DSGcontacts] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DSGcontacts] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DSGcontacts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DSGcontacts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DSGcontacts] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DSGcontacts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DSGcontacts] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DSGcontacts] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DSGcontacts] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DSGcontacts] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DSGcontacts] SET  MULTI_USER 
GO

ALTER DATABASE [DSGcontacts] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DSGcontacts] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DSGcontacts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DSGcontacts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DSGcontacts] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DSGcontacts] SET QUERY_STORE = OFF
GO

USE [DSGcontacts]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DSGcontacts] SET  READ_WRITE 
GO


